### ISSUE TITLE
suzuki miyaura fails

### ISSUE THREAD

**Issue by kjappelbaum** [OpenBioML/chemnlp#477]
```
chemnlp/data/tabular/suzuki_miyaura_sach$ python transform.py
Traceback (most recent call last):
  File "transform.py", line 224, in <module>
    get_and_transform_data()
  File "transform.py", line 202, in get_and_transform_data
    df = add_molecules_and_rxn_smiles_to_df(df)
  File "transform.py", line 151, in add_molecules_and_rxn_smiles_to_df
    df["ligand_SMILES"] = df.Ligand_Short_Hand.apply(
  File "/admin/home-micpie/miniconda3/envs/chemnlp/lib/python3.8/site-packages/pandas/core/series.py", line 4630, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/admin/home-micpie/miniconda3/envs/chemnlp/lib/python3.8/site-packages/pandas/core/apply.py", line 1025, in apply
    return self.apply_standard()
  File "/admin/home-micpie/miniconda3/envs/chemnlp/lib/python3.8/site-packages/pandas/core/apply.py", line 1076, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2834, in pandas._libs.lib.map_infer
  File "transform.py", line 152, in <lambda>
    lambda molecule: canonicalize_smiles(ligand_smiles_dict[molecule])
KeyError: nan
```

**Comment by kjappelbaum** [comment]
cannot reproduce the issue with clean cache

https://app.warp.dev/block/3uSHqpQKpBttQmjbiiLhrg

**Comment by kjappelbaum** [comment]
put perhaps this is due to different handling of `nan`/`None` in different pandas versions? I use `pandas==1.5.2`

**Comment by kjappelbaum** [comment]
fixed in https://github.com/OpenBioML/chemnlp/commit/98132b33e78d4c1d99f83554ef6daa1f02a75349
